
eureka: 
  client: 
    registerWithEureka: true 
    fetchRegistry: true 
    service-url: 
      defaultZone: http://localhost:8761/eureka/ 
  instance: 
    hostname: localhost 
server: 
  port: 8000 
spring: 
  application: 
      name: API-GATEWAY 
  cloud: 
    gateway: 
      routes: 
      - id: CITIZEN-SERVICE 
        uri: 
          lb://CITIZEN-SERVICE 
        predicates: 
        - Path=//citizen/** 
      - id: VACCINATION-CENTER-SERVICE 
        uri: 
          lb://VACCINATION-SERVICE 
        predicates: 
        - Path=//vaccination/**


